Documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

IoT:
 - head-branch: ['^material/iot', 'iot']

Web:
 - head-branch: ['^material/web', 'web']

UI/UX:
 - head-branch: ['^material/uiux', 'uiux']

Android:
 - head-branch: ['^material/android', 'android']
