Documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

IoT:
- head-branch: ['^iot', 'iot']
- changed-files:
  - any-glob-to-any-file: 'internet-of-things/**'

Web:
- head-branch: ['^web', 'web']
- changed-files:
  - any-glob-to-any-file: 'web-development/**'

UI/UX:
- head-branch: ['^uiux', 'uiux']
- changed-files:
  - any-glob-to-any-file: 'ui-ux/**'

Android:
- head-branch: ['^android', 'android']
- changed-files:
  - any-glob-to-any-file: 'android/**'
